title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: ninaadkiran
baseurl: "/Ninaad-Repository2"
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
remote_theme: pages-themes/merlot@v0.2.0
# remote_theme: pages-themes/modernist@v0.2.0
# remote_theme: pages-themes/architect@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
future: true